title: Barnabas Szabo # your name (or website title) here
logo: "/images/ProfileImage.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello World! My name is Branabas Szabo 
  Data and Business Analyst  <br><br>
  <a href="www.linkedin.com/in/barna-szabo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
